### ISSUE TITLE
Cannot build the website because pip fails

### ISSUE THREAD

**Issue by arnaud-m** [csplib/csplib#212]
Hello

I cannot build locally the website because `pip` fails with no such option `--allow-external` during `make`.
I have found this [explanation](https://stackoverflow.com/a/57546316). 
```shell
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --allow-external
<<Finished>>
./internal/scripts/support/problem_creation_dates.sh
# activate virtual python environment
. ./internal/scripts/env/bin/activate && \
./internal/scripts/framework/generate_web_site.py
```

Here a a few information about my configuration.
```shell
$ uname -a 
Linux arrakis 5.13.9-200.fc34.x86_64 #1 SMP Sun Aug 8 14:34:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ python --version
Python 3.9.6
```
Thanks for your help.

**Comment by ChrisJefferson** [comment]
Hi, could you also run `pip --version`? thanks.

**Comment by arnaud-m** [comment]
The following warning message is displayed during `make` : 
```
WARNING: You are using pip version 21.0.1; however, version 21.2.4 is available.
You should consider upgrading via the 'path/to/csplib/internal/scripts/env/bin/python3 -m pip install --upgrade pip' command.
```

However, my system uses another version : 
```
$ pip --version
pip 21.2.4 from /home/nono/.local/lib/python3.9/site-packages/pip (python 3.9)
```

**Comment by ChrisJefferson** [comment]
Could you try getting an update master and see if it fixes it? (you will probably have to type `make clean` before `make` again).

**Comment by arnaud-m** [comment]
The pip error has disappeared, but there are now another error:
```
Building wheels for collected packages: Markdown, MarkupSafe, namedentities, pybtex
  Building wheel for Markdown (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /path/to/csplib/internal/scripts/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wi0ybkfu/markdown_96963980caaa4c4f827932e51ade6e33/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wi0ybkfu/markdown_96963980caaa4c4f827932e51ade6e33/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xts_1cul
       cwd: /tmp/pip-install-wi0ybkfu/markdown_96963980caaa4c4f827932e51ade6e33/
  Complete output (77 lines):
  /tmp/pip-install-wi0ybkfu/markdown_96963980caaa4c4f827932e51ade6e33/setup.py:11: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

...

 ERROR: Failed building wheel for Markdown
```
Thanks again.

**Comment by ChrisJefferson** [comment]
Thanks -- unfortunately this seems hard to fix. Python 3.9 broke the version of Markdown we use (by deleting some internal functions), but upgrading to Markdown 3 breaks lots of other things, as it changed lots of APIs.

If you can install python 3.8 (or any earlier version of python 3) it should work OK.

**Comment by ChrisJefferson** [comment]
I have added a `make docker` option, which requires docker, but pulls down a working ubuntu / python. You can try that if you like, and see if it works!

**Comment by arnaud-m** [comment]
Thanks. I am used to jekyll and I am know that upgrades can be painful.  
I will try the `make docker` alternative soon and update the issue accordingly.

**Comment by arnaud-m** [comment]
I have installed docker. 
```
$ docker --version
Docker version 20.10.8, build 3967b7d
```
`make docker` failed because of a missing dependency 
```
...
Successfully tagged csplib:latest
bash -c 'docker run --user `id -u`:`id -g` -v `pwd`:/dir csplib sh -c "cd /dir;make"'
./internal/scripts/support/problem_creation_dates.sh
# activate virtual python environment
. ./internal/scripts/env/bin/activate && \
./internal/scripts/framework/generate_web_site.py
Traceback (most recent call last):
  File "./internal/scripts/framework/generate_web_site.py", line 7, in <module>
    import util
  File "/dir/internal/scripts/framework/util.py", line 4, in <module>
    import markdown
ModuleNotFoundError: No module named 'markdown'

```
So, I have tried to install dependencies in the docker file.
```dockerfile
RUN apt install -y make pip
RUN pip install -U markdown Jinja2
```

`make docker` still failed because of a dependency problem. 
```
...
Successfully tagged csplib:latest
bash -c 'docker run --user `id -u`:`id -g` -v `pwd`:/dir csplib sh -c "cd /dir;make"'
./internal/scripts/support/problem_creation_dates.sh
# activate virtual python environment
. ./internal/scripts/env/bin/activate && \
./internal/scripts/framework/generate_web_site.py
Traceback (most recent call last):
  File "./internal/scripts/framework/generate_web_site.py", line 25, in <module>
    import jinja2_exts
  File "/dir/internal/scripts/framework/jinja2_exts.py", line 9, in <module>
    from jinja2._compat import text_type
ModuleNotFoundError: No module named 'jinja2._compat'
make: *** [Makefile:5: build] Error 1
make: *** [Makefile:50 : docker] Erreur 2
``` 
The version of jinja2 may be needed ?

By the way,  I am on Fedora 34.

**Comment by ChrisJefferson** [comment]
hi, sorry this is taking so long, thanks for your help!

Can I just check, can you run `make clean` before `make docker`?

**Comment by arnaud-m** [comment]
Indeed, the build is successful after `make clean`.
I should have thought of it myself ...

Thank you for your help.
